#!/usr/bin/env python3

import requests
import datetime
from bs4 import BeautifulSoup
import os

def get_puzzles():
    year = datetime.datetime.now().year

    folder = "puzzles"
    if not os.path.exists(folder):
        os.makedirs(folder)

    for day in range(1, 26):
        print("Getting day " + str(day) + " of year " + str(year))

        content = get_puzzle_from(day, year)
        if content is not None:
            with open(folder + "/day" + str(day) + ".txt", "w") as f:
                f.write(content)

def get_puzzle_from(day, year):
    with open("./.env", "r") as dotenv:
        cookie = dotenv.read()
    
    session = requests.Session()
    session.cookies.set("session", cookie, domain=".adventofcode.com")

    request = session.get("https://adventofcode.com/" + str(year) + "/day/" + str(day))
    if request.status_code != 200:
        if request.status_code == 500:
            print("error: there was a server error. maybe your session cookie is wrong? (500)")
        elif request.status_code == 404:
            print("error: looks like there is no problem on the given date. (404)")
        else:
            print("error: http code " + str(request.status_code))
        return None

    soup = BeautifulSoup(request.text, "html.parser")

    articles = soup.find_all("article", class_="day-desc")
    contents = [article.get_text() for article in articles]

    return contents[0].strip().replace(" ---", " ---\n") + "\n\n" + contents[1].strip().replace(" ---", " ---\n")

if __name__ == "__main__":
    get_puzzles()