#!/usr/bin/env python3

import requests as rt
import datetime as dt
from bs4 import BeautifulSoup
import os

def get_all():
    year = 2024

    folder_name = "puzzles"
    if not os.path.exists(folder_name):
        os.makedirs(folder_name)

    for day in range(1, 26):
        print("Getting day " + str(day) + " of year " + str(year))
        content = get_input(day, year)
        if content is not None:
            with open(folder_name + "/day" + str(day) + ".txt", "w") as f:
                f.write(content)

def get_input(day, year):
    # get the cookie
    cf = open('./.env', 'r')
    cookie = cf.read()
    cf.close()
    
    s = rt.Session()
    s.cookies.set('session', cookie, domain='.adventofcode.com')

    # make request
    r = s.get('https://adventofcode.com/' + str(year) + '/day/' + str(day))
    if r.status_code != 200:
        if r.status_code == 500:
            print('error: there was a server error. maybe your session cookie is wrong? (500)')
        elif r.status_code == 404:
            print('error: looks like there is no problem on the given date. (404)')
        else:
            print('error: http code ' + str(r.status_code))
        return None

    soup = BeautifulSoup(r.text, 'html.parser')

    articles = soup.find_all('article', class_='day-desc')
    contents = [article.get_text() for article in articles]

    return contents[0].strip() + "\n\n" + contents[1].strip()

if __name__ == "__main__":
    get_all()